import { z } from 'zod';

// ── Zod schemas ───────────────────────────────────────────────────────────────

export const LogLevelSchema = z.enum(['log', 'warn', 'error']);
export type LogLevel = z.infer<typeof LogLevelSchema>;

export const ConsoleEventSchema = z.object({
  type: z.literal('console'),
  level: LogLevelSchema,
  args: z.array(z.unknown()),
  stack: z.string().optional(),
  url: z.string(),
  timestamp: z.number(),
  buildSha: z.string().optional(),
  /** SDK that produced this event — 'node' or 'python' for backend events. */
  sdk: z.enum(['node', 'python']).optional(),
  /** Identity of the engineer whose browser captured this event. Set once in the
   *  extension popup or auto-read from VS Code git config. Enables per-engineer
   *  filtering in team mode. */
  userId: z.string().optional(),
  /** Stable per-tab session ID — UUID generated at page load, persisted in
   *  sessionStorage so it survives navigations but resets on new tab.
   *  Used to count unique affected sessions for blast radius quantification. */
  sessionId: z.string().optional(),
  /** Raw navigator.userAgent string — parsed server-side for browser/OS segmentation. */
  userAgent: z.string().max(500).optional(),
  /** The git commit that last touched the primary error frame — populated
   *  automatically after sourcemap resolution when a .git repo is present. */
  gitSuspect: z.object({
    sha: z.string(),
    author: z.string(),
    summary: z.string(),
    /** True when the commit was generated by an AI coding tool (Claude, Cursor, Copilot, etc.) */
    aiGenerated: z.boolean().optional(),
  }).optional(),
});

export const NetworkEventSchema = z.object({
  type: z.literal('network'),
  method: z.string(),
  url: z.string(),
  status: z.number().int(),
  statusText: z.string(),
  duration: z.number(),
  requestBody: z.unknown().optional(),
  requestHeaders: z.record(z.string()).optional(),
  responseBody: z.unknown().optional(),
  responseHeaders: z.record(z.string()).optional(),
  error: z.string().optional(),
  timestamp: z.number(),
  buildSha: z.string().optional(),
  userId: z.string().optional(),
  sessionId: z.string().optional(),
  userAgent: z.string().max(500).optional(),
  /** W3C traceparent or X-Trace-ID extracted from the response headers.
   *  Links browser network events to backend OTel spans across service boundaries. */
  traceId: z.string().optional(),
  /** W3C tracestate header value, preserved verbatim.
   *  Carries vendor-specific routing metadata (e.g. Datadog sampling, Lightstep flags).
   *  Required for multi-vendor trace propagation to survive service boundary crossings. */
  tracestate: z.string().optional(),
  /** W3C Baggage key-value pairs parsed from the baggage request header.
   *  Propagates custom metadata across hops: userId, deploymentEnv, featureFlags, etc.
   *  Only present when the outgoing request carried a baggage header. */
  baggage: z.record(z.string()).optional(),
});

export const ContextSnapshotSchema = z.object({
  type: z.literal('context'),
  trigger: z.enum(['error', 'warn', 'pageload', 'hmr', 'baseline', 'manual']),
  timestamp: z.number(),
  url: z.string(),
  title: z.string(),
  activeElement: z.string().optional(),
  component: z.string().optional(),
  localStorage: z.record(z.string()).default({}),
  sessionStorage: z.record(z.string()).default({}),
  // Layer 1 extensions (optional, backward-compatible)
  componentTree: z.unknown().optional(),
  stateDiff: z.unknown().optional(),
  performanceTrace: z.array(z.unknown()).optional(),
});

export const WebSocketFrameSchema = z.object({
  direction: z.enum(['sent', 'received']),
  data: z.string(),
  timestamp: z.number(),
});

export const WebSocketEventSchema = z.object({
  type: z.literal('websocket'),
  connectionId: z.string(),
  url: z.string(),
  status: z.enum(['open', 'closed', 'error']),
  code: z.number().optional(),
  reason: z.string().optional(),
  error: z.string().optional(),
  frames: z.array(WebSocketFrameSchema).optional().default([]),
  timestamp: z.number(),
});

export const SSEEventSchema = z.object({
  type: z.literal('sse'),
  connectionId: z.string(),
  url: z.string(),
  status: z.enum(['open', 'error']),
  messages: z.array(z.object({
    data: z.string(),
    timestamp: z.number(),
  })).optional().default([]),
  timestamp: z.number(),
});

export const DiagnosticEventSchema = z.object({
  type: z.literal('diagnostic'),
  source: z.string(),
  file: z.string(),
  severity: z.enum(['error', 'warning', 'info', 'hint']),
  message: z.string(),
  code: z.union([z.string(), z.number()]).optional(),
  line: z.number().int(),
  column: z.number().int(),
  timestamp: z.number(),
});

export const TerminalOutputEventSchema = z.object({
  type: z.literal('terminal'),
  terminalName: z.string(),
  data: z.string(),
  timestamp: z.number(),
  /** W3C traceId (32 hex chars) extracted from the log line by the process-watcher.
   *  Present when the backend logged a traceparent header or a known trace ID key.
   *  Enables deterministic browser↔backend joins in get_unified_timeline. */
  traceId: z.string().optional(),
});

export const TestResultEventSchema = z.object({
  type: z.literal('test_result'),
  runner: z.enum(['vitest', 'jest', 'playwright', 'unknown']),
  file: z.string(),
  name: z.string(),
  status: z.enum(['pass', 'fail', 'skip', 'todo']),
  duration: z.number().optional(),
  error: z.object({
    message: z.string(),
    stack: z.string().optional(),
  }).optional(),
  timestamp: z.number(),
});

export const ProcessExitEventSchema = z.object({
  type: z.literal('process_exit'),
  process: z.string(),
  exitCode: z.number().int(),
  reason: z.enum(['oom', 'signal', 'crash', 'normal']),
  signal: z.string().optional(),
  memoryLimitBytes: z.number().optional(),
  timestamp: z.number(),
});

export const CIEventSchema = z.object({
  type: z.literal('ci'),
  provider: z.enum(['github_actions', 'gitlab_ci', 'circleci', 'jenkins', 'azure_devops', 'unknown']).default('unknown'),
  sha: z.string(),
  shortSha: z.string().optional(),
  branch: z.string().optional(),
  workflow: z.string().optional(),
  job: z.string(),
  status: z.enum(['success', 'failure', 'cancelled', 'skipped']),
  durationMs: z.number().optional(),
  url: z.string().optional(),
  failedTests: z.array(z.object({
    name: z.string(),
    error: z.string().optional(),
    file: z.string().optional(),
  })).optional().default([]),
  timestamp: z.number(),
});

export const DeploymentEventSchema = z.object({
  type: z.literal('deployment'),
  environment: z.string(),
  sha: z.string(),
  shortSha: z.string().optional(),
  version: z.string().optional(),
  service: z.string().optional(),
  status: z.enum(['started', 'success', 'failure', 'rollback']),
  url: z.string().optional(),
  actor: z.string().optional(),
  timestamp: z.number(),
});

export const BackendSpanEventSchema = z.object({
  type: z.literal('backend_span'),
  /** Service name — set via MERGEN_NAME env var or auto-detected from package.json */
  service: z.string(),
  /** Matched route pattern, e.g. "/api/users/:id" */
  route: z.string(),
  method: z.string(),
  statusCode: z.number().int(),
  durationMs: z.number(),
  /** W3C traceId (32 hex chars) — the join key linking this span to a browser network event */
  traceId: z.string(),
  spanId: z.string(),
  parentSpanId: z.string().optional(),
  userId: z.string().optional(),
  error: z.string().optional(),
  sdk: z.enum(['node', 'python']),
  timestamp: z.number(),
});

export const BrowserEventSchema = z.discriminatedUnion('type', [
  ConsoleEventSchema,
  NetworkEventSchema,
  ContextSnapshotSchema,
  WebSocketEventSchema,
  SSEEventSchema,
  DiagnosticEventSchema,
  TerminalOutputEventSchema,
  TestResultEventSchema,
  ProcessExitEventSchema,
  CIEventSchema,
  DeploymentEventSchema,
  BackendSpanEventSchema,
]);

export type ConsoleEvent = z.infer<typeof ConsoleEventSchema>;
export type NetworkEvent = z.infer<typeof NetworkEventSchema>;
export type ContextSnapshot = z.infer<typeof ContextSnapshotSchema>;
export type WebSocketEvent = z.infer<typeof WebSocketEventSchema>;
export type SSEEvent = z.infer<typeof SSEEventSchema>;
export type DiagnosticEvent = z.infer<typeof DiagnosticEventSchema>;
export type TerminalOutputEvent = z.infer<typeof TerminalOutputEventSchema>;
export type TestResultEvent = z.infer<typeof TestResultEventSchema>;
export type ProcessExitEvent = z.infer<typeof ProcessExitEventSchema>;
export type CIEvent = z.infer<typeof CIEventSchema>;
export type DeploymentEvent = z.infer<typeof DeploymentEventSchema>;
export type BackendSpanEvent = z.infer<typeof BackendSpanEventSchema>;
export type WebSocketFrame = z.infer<typeof WebSocketFrameSchema>;
export type BrowserEvent = z.infer<typeof BrowserEventSchema>;
