/**
 * ai-commit.ts — Detect AI-generated commits from commit metadata.
 *
 * Checks commit message and author against known AI coding tool signatures.
 * Used by causal analysis, postmortem generation, and the change timeline tool
 * to tag AI-generated code in the blast radius.
 */

const AI_AUTHOR_RE = /\b(claude|cursor|copilot|windsurf|codeium|tabnine|devin|ghostwriter|codex)\b/i;

const AI_SUMMARY_RE = /\b(claude|cursor|copilot|windsurf|codeium|tabnine|devin|ghostwriter|codex)\b|co-authored-by:\s*(claude|cursor|copilot|windsurf|codeium|devin)|generated (by|with) (ai|claude|cursor|copilot)|ai[- ]generated|ai[- ]written|auto[- ]generated by/i;

export interface AiCommitSignal {
  detected: boolean;
  tool: string | null;
}

export function detectAiCommit(summary: string, author?: string): AiCommitSignal {
  const text = [summary, author ?? ''].join(' ');

  const authorMatch = author ? AI_AUTHOR_RE.exec(author) : null;
  if (authorMatch) return { detected: true, tool: authorMatch[1].toLowerCase() };

  const summaryMatch = AI_SUMMARY_RE.exec(text);
  if (summaryMatch) {
    const tool = (summaryMatch[1] ?? summaryMatch[2] ?? 'ai').toLowerCase();
    return { detected: true, tool };
  }

  return { detected: false, tool: null };
}
